## Deplacement d'un individu

In [1]:
import matplotlib

In [2]:
#les identifiants des pokemons:
#11**:rattata male
#12**:rattata femelle
#21**:manglouton male
#22**:manglouton femelle
#31**:rattatac male
#32**:rattatac femelle
#41**:argouste male
#42**:argouste femelle
#** représente l'âge de l'individu

In [3]:
import numpy as numpy

In [4]:
import numpy as np
#case vide
v=0
N=50
M=np.zeros((N,N))



In [5]:
#test
M[1][1]=1200
M[1][2]=1100
M


array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,  1200.,  1100., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [6]:
np.where(M == 1202)

(array([], dtype=int64), array([], dtype=int64))

In [7]:
M=np.zeros((N,N))
M[1][1]=1200
M[1][2]=1100
def vieillesse(M,i,j):
    if M[i][j]%100==99:
        M[i][j]=0
    else:
        M[i][j]=M[i][j]+1
        n=np.random.choice(99)      
        if M[i][j]%100>n:
            M[i][j]=0 
    return
vieillesse(M,1,1)
vieillesse(M,1,2)
M

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,  1201.,  1101., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [8]:
def position(i,j):
    if i==0:
        if j==0:
            return "CoinSupG"
        elif j==len(M)-1:
            return "CoinSupD"
        else:
            return "CotHaut"
    elif j==0:
        if i==len(M)-1:
            return "CoinBasG"
        else :
            return "CotG"
    elif j==len(M)-1:
        if i==len(M)-1:
            return "CoinBasD"
        else:
            return "CotD"
    elif i==len(M):
        return "CoteBas"
    else:
        return "Milieu"
position(1,1)

'Milieu'

In [9]:
M=np.zeros((N,N))
M[1][1]=1200
M[1][2]=1100
def voisin(i,j):
    Le=[]#environnement
    if position(i,j)=="Milieu":
        Le=[(i-1,j-1),(i-1,j),(i-1,j+1),(i,j-1),(i,j+1),(i+1,j-1),(i+1,j),(i+1,j+1)]
    elif position(i,j)=="CoinSupG":
        Le=[(i,j+1),(i+1,j),(i+1,j+1)]
    elif position(i,j)=="CoinSupD":
        Le=[(i,j-1),(i+1,j),(i+1,j-1)]
    elif position(i,j)=="CoinBasG":
        Le=[(i,j+1),(i-1,j),(i-1,j+1)]
    elif position(i,j)=="CoinBasD":
        Le=[(i,j-1),(i-1,j),(i-1,j-1)]
    elif position(i,j)=="CotD":
        Le=[(i,j-1),(i-1,j),(i-1,j-1),(i+1,j),(i+1,j-1)]
    elif position(i,j)=="CotG":
        Le=[(i,j+1),(i-1,j),(i-1,j+1),(i+1,j+1)]
    elif position(i,j)=="CotBas":
        Le=[(i,j-1),(i-1,j-1),(i-1,j),(i-1,j+1),(i,j+1)]
    elif position(i,j)=="CotHaut":
        Le=[(i,j-1),(i+1,j-1),(i+1,j),(i+1,j+1),(i,j+1)]
    return Le

le=voisin(1,1)
le

[(0, 0), (0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 2)]

In [12]:

Vide=[]#liste des emplacements vides aux alentours
Ma=[]#liste des Mangloutons aux alentours
#Ra=[]#liste des Rattatas aux alentours
Ar=[]#liste des Argoustes aux alentours
#Rac=[]#liste des Rattatacs aux alentours
acc=[]#liste des potentiels partenaires pour l'accouplement


def rattataM(Le):
    for x in Le:
        i,j=x
        if M[i][j]//1000==2:
            Ma.append(x)
        elif M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return

def rattataF(Le):
    for x in Le:
        i,j=x
        if M[i][j]//100==11 or M[i][j]//100==31:
            acc.append(x)
        elif M[i][j]//1000==2:
            Ma.append(x)
        elif M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return        

def rattatacM(Le):
    for x in Le:
        i,j=x
        if M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return

def rattatacF(Le):
    for x in Le:
        i,j=x
        if M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]//100==11 or M[i][j]//100==31:
            acc.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return
            
def mangloutonM(Le):
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append(x)
    return       
            
            
def mangloutonF(Le):
    for x in Le:
        i,j=x
        if M[i][j]//100==21 or M[i][j]//100==41:
            acc.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return

def argousteM(Le):
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append(x)
    return

def argousteF(Le):
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append(x)
        elif M[i][j]//100==21 or M[i][j]//100==41:
            acc.append(x)
    return

rattataF(le)
acc


[(1, 2)]

In [57]:
Vide=[]#liste des emplacements vides aux alentours
Ma=[]#liste des Mangloutons aux alentours
#Ra=[]#liste des Rattatas aux alentours
Ar=[]#liste des Argoustes aux alentours
#Rac=[]#liste des Rattatacs aux alentours
acc=[]#liste des potentiels partenaires pour l'accouplement

def evolution(i,j):
    if M[i][j]%100>=20 and (M[i][j]//1000==1 or M[i][j]//1000==2):
        n=np.random.choice(np.arange(0,10))
        if n*(M[i][j]%100-10)>50:
            M[i][j]=2000+M[i][j]
    return        
def manger(Ma,Ar,M,i,j):
    n=np.random.choice(np.arange(0,100))
    if M[i][j]//1000==1:
        if n<10*(len(Ma)+len(Ar)):
            M[i][j]=0
    elif M[i][j]//1000==3:
        if n<10*len(Ma):
            M[i][j]=0
    return i,j

def accouplement(i,j):
    n=np.random.choice(np.arange(0,100))
    if len(acc)*10 > n:
        e=np.random.choice(np.arange(0,len(Vide)))
        sexe=np.random.choice(np.arange(1,2))
        x,y=Vide[e]
        M[x,y]=M[i][j]//1000+sexe*100
    return
                       
def deplacement(i,j):
    e=np.random.choice(np.arrange(0,len(Vide)))
    x,y=Vide[e]
    M[x,y]=M[i][j]
    M[i][j]=0    
    return    

def regroupement(M,Vide,i,j):
    Voisin2=[]
    c=0
    Rattatac=[]
    for s in Vide:
        c=0
        x,y=s
        if x==i-1 and y==j-1:
            Voisin2=[(i-2,j-2),(i-2,j-1),(i-2,j),(i-1,j-2),(i-1,j),(i,j-2),(i,j-1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i-1 and y==j:
            Voisin2=[(i-2,j-1),(i-2,j),(i-2,j+1),(i-1,j-1),(i-1,j+1),(i,j-1),(i,j+1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
        if x==i-1 and y==j+1:
            Voisin2=[(i-2,j),(i-2,j+1),(i-2,j+2),(i-1,j),(i-1,j+2),(i,j+1),(i,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i and y==j-1:
            Voisin2=[(i-1,j-2),(i-1,j-1),(i-1,j),(i,j-2),(i+1,j-2),(i+1,j-1),(i+1,j)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i and y==j+1:
            Voisin2=[(i-1,j),(i-1,j+1),(i-1,j+2),(i,j+2),(i+1,j),(i+1,j+1),(i+1,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j-1:
            Voisin2=[(i,j-2),(i,j-1),(i+1,j-2),(i+1,j),(i+2,j-2),(i+2,j-1),(i+2,j)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j:
            Voisin2=[(i,j-1),(i,j+1),(i+1,j-1),(i+1,j+1),(i+2,j-1),(i+2,j),(i+2,j+1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j+1:
            Voisin2=[(i,j+1),(i,j+2),(i+1,j),(i+1,j+2),(i+2,j),(i+2,j+1),(i+2,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]                       

In [62]:
def matrice_alea():
    N=50
    M=np.zeros((N,N))
    for i in range (0,N):
        for j in range (0,N):
            al_e=np.random.choice(np.arange(0,4))
            al_s=np.random.choice(np.arange(1,3))
            al_a=np.random.choice(np.arange(0,100))
            if al_e==0:
                M[i][j]=1000+al_s*100+al_a
            elif al_e==1:
                M[i][j]=2000+al_s*100+al_a
            elif al_e==2:
                M[i][j]=3000+al_s*100+al_a
            elif al_e==3:
                M[i][j]=4000+al_s*100+al_a
    return M
Matrice=matrice_alea()
Matrice

array([[ 3200.,  3178.,  4153., ...,  3153.,  2169.,  1221.],
       [ 2132.,  3158.,  1268., ...,  4179.,  1251.,  4254.],
       [ 4174.,  3272.,  4239., ...,  1145.,  3207.,  3256.],
       ..., 
       [ 3190.,  3192.,  1149., ...,  3213.,  3142.,  4213.],
       [ 4297.,  2194.,  2138., ...,  4232.,  1196.,  3122.],
       [ 1277.,  3258.,  4146., ...,  2158.,  1115.,  4112.]])

In [63]:

def simulation(M):
    M=matrice_alea()
    for i in range(0,len(M)):
        for j in range(0,len(M)):
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            if M[i][j]//100==11:
                rattataM(Le)
            elif M[i][j]//100==12:   
                rattataF(Le)
            elif M[i][j]//100==31:
                rattatacM(Le)
            elif M[i][j]//100==32:
                rattatacF(Le)
            elif M[i][j]//100==21:
                mangloutonM(Le)
            elif M[i][j]//100==22:
                mangloutonF(Le)
            elif M[i][j]//100==41:
                argousteM(Le)
            elif M[i][j]//100==42:
                argousteF(Le)
            if len(Ma)>0 or len(Ar)>0:
                manger(Ma,Ar,M,i,j)
            elif len(acc)>0 and len(Vide)>0:
                accouplement() 
            elif len(Vide)>0:
                deplacement()
            evolution(i,j)
            vieillesse(M,i,j)
m=simulation(M)

IndexError: index 50 is out of bounds for axis 0 with size 50

In [ ]:
  M=[),(i+1,j+1),(i,j+1)]

In [16]:
 np.random.choice(np.arange(0,3))


2

In [17]:
np.random.choice(99)


8

In [34]:
 np.random.choice(np.arange(1,3))

1

In [40]:
np.random.choice(np.arange(0,4))

0

In [ ]:
import matplotlib.pyplot as plt
size = np.array(cells.shape)
dpi = 50.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig = plt.figure(figsize = figsize, dpi = dpi, facecolor = "white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon = False)
im=plt.imshow(cells, interpolation = 'nearest', cmap = plt.cm.gray_r)
plt.xticks([]), plt.yticks([])

import matplotlib.animation as a
def update():
    iterate(cells)
    im.set_array(cells)
    return im,

ani = a.FuncAnimation(fig, update, frames=range(20), interval=50)
plt.show()