## Deplacement d'un individu

In [2]:
import matplotlib

In [3]:
#les identifiants des pokemons:
#11**:rattata male
#12**:rattata femelle
#21**:manglouton male
#22**:manglouton femelle
#31**:rattatac male
#32**:rattatac femelle
#41**:argouste male
#42**:argouste femelle
#** représente l'âge de l'individu

In [4]:
import numpy as numpy

In [5]:
import numpy as np
#case vide
v=0
N=50
M=np.zeros((N,N))



In [6]:
#test
M[1][1]=1200
M[1][2]=1100
M


array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,  1200.,  1100., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [7]:
np.where(M == 1202)

(array([], dtype=int64), array([], dtype=int64))

In [35]:
M=np.zeros((N,N))
M[1][1]=1200
M[1][2]=1100
def vieillesse(M,i,j):
    if M[i][j]%100==99:
        M[i][j]=0
    elif M[i][j]/100==21 or M[i][j]/100==22 or M[i][j]/100==41 or M[i][j]/100==42:
        M[i][j]=M[i][j]+1
        n=np.random.choice(99)      
        if M[i][j]%100>n:
            M[i][j]=0 
    else:
        M[i][j]=M[i][j]+1
        n=np.random.choice(99)      
        if (M[i][j]%100)/2>n:
            M[i][j]=0 
    return
vieillesse(M,1,1)
vieillesse(M,1,2)
M

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,  1201.,  1101., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [9]:
def position(i,j):
    if i==0:
        if j==0:
            return "CoinSupG"
        elif j==len(M)-1:
            return "CoinSupD"
        else:
            return "CotHaut"
    elif j==0:
        if i==len(M)-1:
            return "CoinBasG"
        else :
            return "CotG"
    elif j==len(M)-1:
        if i==len(M)-1:
            return "CoinBasD"
        else:
            return "CotD"
    elif i==len(M)-1:
        return "CoteBas"
    else:
        return "Milieu"
position(1,1)

'Milieu'

In [10]:
N=50
M=np.zeros((N,N))
position(N-1,N-1)

'CoinBasD'

In [11]:
M=np.zeros((N,N))
M[1][1]=1200
M[1][2]=1100
def voisin(i,j):
    Le=[]#environnement
    if position(i,j)=="Milieu":
        Le=[(i-1,j-1),(i-1,j),(i-1,j+1),(i,j-1),(i,j+1),(i+1,j-1),(i+1,j),(i+1,j+1)]
    elif position(i,j)=="CoinSupG":
        Le=[(i,j+1),(i+1,j),(i+1,j+1)]
    elif position(i,j)=="CoinSupD":
        Le=[(i,j-1),(i+1,j),(i+1,j-1)]
    elif position(i,j)=="CoinBasG":
        Le=[(i,j+1),(i-1,j),(i-1,j+1)]
    elif position(i,j)=="CoinBasD":
        Le=[(i,j-1),(i-1,j),(i-1,j-1)]
    elif position(i,j)=="CotD":
        Le=[(i,j-1),(i-1,j),(i-1,j-1),(i+1,j),(i+1,j-1)]
    elif position(i,j)=="CotG":
        Le=[(i,j+1),(i-1,j),(i-1,j+1),(i+1,j+1)]
    elif position(i,j)=="CotBas":
        Le=[(i,j-1),(i-1,j-1),(i-1,j),(i-1,j+1),(i,j+1)]
    elif position(i,j)=="CotHaut":
        Le=[(i,j-1),(i+1,j-1),(i+1,j),(i+1,j+1),(i,j+1)]
    return Le

le=voisin(0,N-1)
le

[(0, 48), (1, 49), (1, 48)]

In [12]:
position(49,0)

'CoinBasG'

In [93]:

Vide=[]#liste des emplacements vides aux alentours
Ma=[]#liste des Mangloutons aux alentours
Ra=[]#liste des Rattatas aux alentours
Ar=[]#liste des Argoustes aux alentours
Rac=[]#liste des Rattatacs aux alentours
acc=[]#liste des potentiels partenaires pour l'accouplement

#return (acc,Ra,Rac,Ma,Ar,Vide)
def rattataM(Le, M):
    Ar=[]
    Ma=[]
    Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//1000==2:
            Ma.append((i,j))
        elif M[i][j]//1000==4:
            Ar.append((i,j))
        elif M[i][j]==0:
            Vide.append((i,j))
        
    return ([],Ma,Ar,Vide)

def rattataF(Le,M):
    Ar=[]
    Vide=[]
    acc=[]
    Ma=[]
    for x in Le:
        i,j=x
        if M[i][j]//100==11 or M[i][j]//100==31:
            acc.append((i,j))
        elif M[i][j]//1000==2:
            Ma.append((i,j))
        elif M[i][j]//1000==4:
            Ar.append((i,j))
        elif M[i][j]==0:
            Vide.append((i,j))
    return  (acc,Ma,Ar,Vide)      

def rattatacM(Le,M):
    Ar=[]
    Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//1000==4:
            Ar.append((i,j))
        elif M[i][j]==0:
            Vide.append((i,j))
    return ([],[],Ar,Vide)

def rattatacF(Le,M):
    Ar=[]
    acc=[]
    Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//1000==4:
            Ar.append((i,j))
        elif M[i][j]//100==11 or M[i][j]//100==31:
            acc.append((i,j))
        elif M[i][j]==0:
            Vide.append((i,j))
    return (acc,[],Ar,Vide)
            
def mangloutonM(Le,M):
    Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append((i,j))
    return  ([],[],[],Vide)     
            
            
def mangloutonF(Le,M):
    acc=[]
    Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//100==21 or M[i][j]//100==41:
            acc.append((i,j))
        elif M[i][j]==0:
            Vide.append((i,j))
    return (acc,[],[],Vide)

def argousteM(Le,M):
    Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append((i,j))
    return ([],[],[],Vide)

def argousteF(Le,M):
    Vide=[]
    acc=[]
    for x in Le:
        i,j=x
        if M[i][j]//100==21 or M[i][j]//100==41:
            acc.append((i,j))
        elif M[i][j]==0:
            Vide.append((i,j))       
    return (acc,[],[],Vide)




In [14]:
1200//1000*1000


1000

In [92]:
Vide=[]#liste des emplacements vides aux alentours
Ma=[]#liste des Mangloutons aux alentours
Ra=[]#liste des Rattatas aux alentours
Ar=[]#liste des Argoustes aux alentours
Rac=[]#liste des Rattatacs aux alentours
acc=[]#liste des potentiels partenaires pour l'accouplement

def evolution(i,j,M):
    if M[i][j]%100>=20 and (M[i][j]//1000==1 or M[i][j]//1000==2):
        M[i][j]=2000+M[i][j]
        #print(M[i][j])
    return M       
def manger(Ar,Ma,M,i,j):
    n=np.random.choice(np.arange(1,101))
    if M[i][j]//1000==1:
        if (len(Ma)>0 or len(Ar)>0) and n<5:
            M[i][j]=0
            if len(Ma)>0:
                x,y=Ma[0]
                M[i,j]=M[x,y]
                M[x,y]=0
            elif len(Ar)>0:
                x,y=Ar[0]
                M[i,j]=M[x,y]
                M[x,y]=0
    elif M[i][j]//1000==3:
        if len(Ar)>0 and n<5:
            M[i][j]=0
            x,y=Ar[0]
            M[i,j]=M[x,y]
            M[x,y]=0
    return M

def accouplement_m(i,j,Vide,acc,M):
    n=np.random.choice(np.arange(0,100))
    if len(acc)*10 > n:
        e=np.random.choice(np.arange(0,len(Vide)))
        sexe=np.random.choice(np.arange(1,3))
        x,y=Vide[e]
        M[x][y]=M[i][j]//1000*1000+sexe*100
    return M

def accouplement_r(i,j,Vide,acc,M):#attention tu as changé le nom de accouplement pour en faire 2
    
    e=np.random.choice(np.arange(0,len(Vide)))
    sexe=np.random.choice(np.arange(1,3))
    x,y=Vide[e]
    M[x][y]=M[i][j]//1000*1000+sexe*100
    return M
                       
def deplacement(i,j,Vide,M):
    e=np.random.choice(np.arange(0,len(Vide)))
    x,y=Vide[e]
    M[x,y]=M[i][j]
    M[i][j]=0    
    return M 
M=np.zeros((50,50))
M[0,0]=1200
M[0,1]=1100
deplacement(0,0,[(1,1),(1,0)],M)

def famine(i,j,Ar,Ma,M):
    if (M[i][j]//1000==2 or M[i][j]//1000==4) and len(Ar)+len(Ma)==8:
        M[i,j]=0
    return M
def famine2(i,j,Vide,M):
    if len(Vide)==0:
        M[i,j]=0
    return M
M    

array([[    0.,  1100.,     0., ...,     0.,     0.,     0.],
       [    0.,  1200.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

#def regroupement(M,Vide,i,j):
    Voisin2=[]
    c=0
    Rattatac=[]
    for s in Vide:
        c=0
        x,y=s
        if x==i-1 and y==j-1:
            Voisin2=[(i-2,j-2),(i-2,j-1),(i-2,j),(i-1,j-2),(i-1,j),(i,j-2),(i,j-1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                   if c==1:
                        Rattatac.append[m]
        if x==i-1 and y==j:
            Voisin2=[(i-2,j-1),(i-2,j),(i-2,j+1),(i-1,j-1),(i-1,j+1),(i,j-1),(i,j+1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
        if x==i-1 and y==j+1:
            Voisin2=[(i-2,j),(i-2,j+1),(i-2,j+2),(i-1,j),(i-1,j+2),(i,j+1),(i,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i and y==j-1:
            Voisin2=[(i-1,j-2),(i-1,j-1),(i-1,j),(i,j-2),(i+1,j-2),(i+1,j-1),(i+1,j)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i and y==j+1:
            Voisin2=[(i-1,j),(i-1,j+1),(i-1,j+2),(i,j+2),(i+1,j),(i+1,j+1),(i+1,j+2)]
          for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j-1:
            Voisin2=[(i,j-2),(i,j-1),(i+1,j-2),(i+1,j),(i+2,j-2),(i+2,j-1),(i+2,j)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j:
            Voisin2=[(i,j-1),(i,j+1),(i+1,j-1),(i+1,j+1),(i+2,j-1),(i+2,j),(i+2,j+1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j+1:
            Voisin2=[(i,j+1),(i,j+2),(i+1,j),(i+1,j+2),(i+2,j),(i+2,j+1),(i+2,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]    

In [16]:
def matrice_alea(N):
    
    M=np.zeros((N,N))
    for i in range (0,N):
        for j in range (0,N):
            al_e=np.random.choice(np.arange(0,5))
            al_s=np.random.choice(np.arange(1,3))
            al_a=np.random.choice(np.arange(0,100))
            if al_e==0:
                M[i][j]=1000+al_s*100+al_a
            elif al_e==1:
                M[i][j]=2000+al_s*100+al_a
            elif al_e==2:
                M[i][j]=3000+al_s*100+al_a
            elif al_e==3:
                M[i][j]=4000+al_s*100+al_a
            elif al_e==4:
                M[i][j]=0
    return M
Matrice=matrice_alea(50)
Matrice

array([[ 1243.,  2286.,  1142., ...,  4165.,     0.,  4290.],
       [    0.,  3297.,  2233., ...,  4127.,     0.,  4169.],
       [ 3151.,  4196.,  1289., ...,  1154.,  2249.,  1248.],
       ..., 
       [ 4160.,  1193.,  1146., ...,  2245.,  1164.,  4198.],
       [ 3138.,  1255.,  2204., ...,  1200.,  1143.,     0.],
       [ 3235.,  3102.,  1163., ...,     0.,  1115.,     0.]])

In [17]:
voisin(49,1)

[]

In [18]:
M[0,3]=1235
evolution(0,3)


3235.0


array([[    0.,  1100.,     0., ...,     0.,     0.,     0.],
       [ 1200.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [19]:
M[0,0]=1245
M[0,1]=1114
M[1,0]=0
vide=[(1,0)]
acc=[(0,1)]
accouplement(0,0,vide,acc)
M[(0,0)]
M[1,0]

NameError: name 'accouplement' is not defined

In [20]:
def list_ind(M):
    L_ind=[]
    for i in range (0,len(M)):
        for j in range (0,len(M)):
            if M[i][j]!=0:
                L_ind.append((i,j))
    return L_ind
list_ind(Matrice)

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 5),
 (0, 6),
 (0, 9),
 (0, 10),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 20),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 35),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 49),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 6),
 (1, 7),
 (1, 8),
 (1, 9),
 (1, 10),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 20),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 30),
 (1, 31),
 (1, 32),
 (1, 34),
 (1, 35),
 (1, 36),
 (1, 37),
 (1, 38),
 (1, 39),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 46),
 (1, 47),
 (1, 49),
 (2, 0),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 10),
 (2, 12),
 (2, 13),
 (2, 15),
 (2, 17),
 (2, 18),
 (2, 19),
 (2, 20),
 (2, 22),
 (2, 23),
 (2, 24),
 (2, 25),
 (2, 26),
 (2, 27),
 (2, 28),
 (2

In [ ]:
def individu(x,M):
    i,j=x
    return M[i][j]

#simulation  avec une matrice aléatoire et tous les individus possibles cad rattata, manglouton, rattattac et argouste (a effacer eventuellement)
def simulation():
    M=matrice_alea(50)
    for i in range(0,len(M)):
        for j in range(0,len(M)):
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            
            if M[i][j]//100==11:
                rattataM(Le,Ar,Ma,Vide)
            elif M[i][j]//100==12:   
                rattataF(Le,acc,Ma,Ar,Vide)
            elif M[i][j]//100==31:
                rattatacM(Le,Ar,Vide)
            elif M[i][j]//100==32:
                rattatacF(Le,Ar,acc,Vide)
            elif M[i][j]//100==21:
                mangloutonM(Le,Vide)
            elif M[i][j]//100==22:
                mangloutonF(Le,acc,Vide)
            elif M[i][j]//100==41:
                argousteM(Le,Vide)
            elif M[i][j]//100==42:
                argousteF(Le,Vide,acc)
            if len(Ma)>0 or len(Ar)>0:
                manger(Ma,Ar,M,i,j)
            elif len(acc)>0 and len(Vide)>0:
                accouplement(i,j,Vide) 
            elif len(Vide)>0:
                deplacement(i,j,Vide)
            evolution(i,j)
            vieillesse(M,i,j)
                
    return M
simulation()

In [61]:
#simulation  avec une matrice aléatoire et tous les individus possibles cad rattata, manglouton, rattattac et argoust
def simulation_aleatoire_toutes_regles():
        M=matrice_alea(50)
        for x in list_ind(M):
            i,j=x
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            
            if M[i][j]//100==11:
                acc,Ma,Ar,Vide=rattataM(Le,M)
            elif M[i][j]//100==12:   
                acc,Ma,Ar,Vide=rattataF(Le,M)
            elif M[i][j]//100==31:
                acc,Ma,Ar,Vide=rattatacM(Le,M)
            elif M[i][j]//100==32:
                acc,Ma,Ar,Vide=rattatacF(Le,M)
            elif M[i][j]//100==21:
                acc,Ma,Ar,Vide=mangloutonM(Le,M)
            elif M[i][j]//100==22:
                acc,Ma,Ar,Vide=mangloutonF(Le,M)
            elif M[i][j]//100==41:
                acc,Ma,Ar,Vide=argousteM(Le,M)
            elif M[i][j]//100==42:
                acc,Ma,Ar,Vide=argousteF(Le,M)
            if len(Ma)>0 or len(Ar)>0:
                manger(Ma,Ar,M,i,j)
            elif len(acc)>0 and len(Vide)>0:
                accouplement(i,j,Vide,acc,M) 
            elif len(Vide)>0:
                deplacement(i,j,Vide,M)
            evolution(i,j,M)
            vieillesse(M,i,j)
                
        return M
simulation_aleatoire_toutes_regles()

array([[  2.20000000e+03,   2.20000000e+03,   3.28700000e+03, ...,
          3.27800000e+03,   3.13900000e+03,   2.10000000e+03],
       [  2.10000000e+03,   4.27100000e+03,   1.00000000e+00, ...,
          1.00000000e+00,   3.22000000e+03,   4.28000000e+03],
       [  4.10400000e+03,   1.00000000e+00,   2.20000000e+03, ...,
          1.00000000e+00,   4.13500000e+03,   3.27800000e+03],
       ..., 
       [  0.00000000e+00,   1.00000000e+00,   0.00000000e+00, ...,
          4.10000000e+03,   2.10000000e+03,   3.29400000e+03],
       [  2.11700000e+03,   3.13500000e+03,   3.24400000e+03, ...,
          3.18500000e+03,   4.29600000e+03,   3.26300000e+03],
       [  4.21000000e+03,   0.00000000e+00,   3.16800000e+03, ...,
          2.10000000e+03,   3.17600000e+03,   4.26200000e+03]])

In [94]:
#on veut donc faire un modele avec un seul rattata male (position:0,0) et une seule rattata femelle 
#(position:0,1) pour voir l evolution de la population
#pas d evolution, pas de manglouton, que l accouplement et la vieillesse

def simulation_rattata(temps):
    M=np.zeros((50,50))
    M[0][0]=1100
    M[0][1]=1200
    for i in range(0,temps):
        for x in list_ind(M):
            i,j=x
            Le=voisin(i,j)
            if M[i][j]//100==11:
                acc,Ma,Ar,Vide=rattataM(Le, M)                
            elif M[i][j]//100==12:   
                acc,Ma,Ar,Vide=rattataF(Le,M)            
            vieillesse(M,i,j)
            if M[i,j]!=0:
                if len(acc)>0 and len(Vide)>0:
                    accouplement_r(i,j,Vide,acc,M)
                elif len(Vide)>0:
                    deplacement(i,j,Vide,M)

           
                
    return M
print_matrice(simulation_rattata(150))
#en conclusion, pas assez d'individus pour que les deux individus introduits sur l ile puissent se reproduire,
#faible chance pour l espece de coloniser l ile

1118 1200 1206 1116 1117 1204 1203 1202 1205 1225 1221 1119 1105 1131 1119 1113 1111 1104 1206 1209 1109 1109 1107 1106 1103 1203 1206 1218 1112 1112 1111 1104 1210 1216 1209 1213 1201 1206 1205 1208 1108 1124 1103 1101 1206 1202 1224 1112 1106 1103 
1200 1204 1203 1209 1112 1209 1204 1215 1127 1106 1105 1112 1112 1104 1102 1100 1205 1209 1216 1103 1202 1106 1101 1215 1218 1111 1202 1100 1207 1113 1110 1108 1203 1202 1204 1207 1209 1124 1108 1111 1200 1204 1205 1206 1106 1104 1203 1207 1201 1210 
1124 1115 1213 1106 1201 1205 1111 1110 1202 1207 1205 1121 1105 1101 1200 1102 1100 1232 1112 1118 1117 1120 1108 1201 1204 1205 1110 1108 1102 1206 1112 1205 1208 1218 1223 1112 1210 1209 1202 1100 1218 1101 1217 1101 1112 1100 1216 1108 1208 1100 
1125 1232 1106 1104 1219 1115 1205 1200 1207 1217 1113 1102 1100 1205 1207 1121 1102 1204 1205 1116 1112 1101 1204 1205 1216 1228 1200 1207 1122 1107 1105 1209 1121 1119 1200 1209 1108 1202 1204 1101 1208 1213 1114 1102 1100 1210 1226 1111 1201 12

In [26]:
def print_matrice(mat):
    (n,m) = mat.shape
    for i in range(n):
        for j in range(m):
            print(int(mat[i,j]), end=" ")
        print()

In [104]:
#autre modele qui a partir du precedent prend en compte l'introduction de manglouton sur l ile
#les mangloutons arrivent aussi sur la premiere rangee ssi il y a un emplacement vide
#le sexe et l age des individus initialisés seront definis de maniere aléatoire
def simulation_rattata_manglouton(t1,t2):
    M=simulation_rattata(t1)
    for a in range(0,50):
        M[49][a]=2000+np.random.choice(np.arange(1,3))*100
    for i in range(0,t2):
        for x in list_ind(M):
            i,j=x
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            if M[i][j]//100==11:
                acc,Ma,Ar,Vide=rattataM(Le,M)
            elif M[i][j]//100==12:   
                acc,Ma,Ar,Vide=rattataF(Le,M)
            elif M[i][j]//100==21:
                acc,Ma,Ar,Vide=mangloutonM(Le,M)
            elif M[i][j]//100==22:
                acc,Ma,Ar,Vide=mangloutonF(Le,M)
            vieillesse(M,i,j)
            if M[i][j]!=0:
                if len(Ma)>0 or len(Ar)>0:
                    manger(Ma,Ar,M,i,j)
                elif len(acc)>0 and len(Vide)>0:
                    accouplement(i,j,Vide,acc,M) 
                elif len(Vide)>0:
                    deplacement(i,j,Vide,M)
            
    return M
print_matrice(simulation_rattata_manglouton(50,50))

1104 1109 1102 1109 1201 1210 1105 1202 1201 1206 1115 1103 1208 1100 1209 1124 1121 1208 1202 1220 1223 1122 1110 1103 1211 1104 1100 1100 1206 1213 1218 1104 1219 1132 1202 1215 1216 1108 1111 1202 1220 1101 1216 1115 1212 1121 1112 1112 1114 1127 
1110 1208 1103 1101 1218 1111 1103 1217 1203 1220 1113 1203 1106 1202 1209 1215 1115 1111 1108 1106 1203 1215 1112 1108 1102 1206 1211 1202 1219 1118 1208 1205 1202 1228 1206 1227 1123 1201 1206 1105 1102 1218 1214 1109 1116 1208 1207 1206 1120 1105 
1110 1205 1209 1212 1221 1106 1219 1235 1119 1129 1122 1202 1218 1212 1221 1224 1111 1122 1123 1106 1103 1204 1101 1212 1217 1113 1227 1102 1100 1108 1112 1118 1104 1100 1213 1125 1110 1206 1100 1219 1214 1101 1217 1214 1214 1202 1211 1111 1118 1201 
1202 1212 1117 1118 1111 1107 1203 1212 1124 1115 1100 1201 1200 1205 1213 1108 1108 1105 1101 1203 1212 1212 1213 1217 1111 1108 1101 1100 1207 1212 1104 1213 1110 1202 1205 1100 1205 1226 1223 1104 1101 1218 1216 1100 1213 1213 1107 1201 1202 12

In [ ]:
se = set((4,5,2,3,6,7))

In [50]:
def simulation_rattata_manglouton2(t):
    M=np.zeros((50,50))
    M[0,0]=1100
    M[0,1]=1200
    M[0,49]=2100
    M[0,48]=2200
    for i in range(0,t):
        for x in list_ind(M):
            i,j=x
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            if M[i][j]//100==11:
                acc,Ma,Ar,Vide=rattataM(Le,M)
            elif M[i][j]//100==12:   
                acc,Ma,Ar,Vide=rattataF(Le,M)
            elif M[i][j]//100==21:
                acc,Ma,Ar,Vide=mangloutonM(Le,M)
            elif M[i][j]//100==22:
                acc,Ma,Ar,Vide=mangloutonF(Le,M)
            vieillesse(M,i,j)
            if M[i][j]!=0:
                if len(Ma)>0 or len(Ar)>0:
                    manger(Ma,Ar,M,i,j)
                elif len(acc)>0 and len(Vide)>0:
                    accouplement(i,j,Vide,acc,M) 
                elif len(Vide)>0:
                    deplacement(i,j,Vide,M)
            
    return M
print_matrice(simulation_rattata_manglouton2(1000))

2121 2120 2102 2213 2211 2207 2104 2208 2125 2123 2208 2111 2208 2204 2208 2100 2234 2106 2101 2204 2211 2105 2203 2201 2213 2115 2101 2203 2207 2208 2210 2108 2112 2115 2113 2108 2110 2127 2119 2201 2107 2202 2101 2203 2206 2215 2230 2137 2103 2200 
2107 2106 2102 2205 2208 2101 2216 2217 2100 2223 2112 2207 2201 2208 2204 2206 2201 2217 2117 2221 2101 2213 2219 2101 2200 2203 2219 2106 2210 2211 2112 2210 2214 2120 2109 2111 2109 2104 2202 2204 2208 2205 2215 2222 2109 2100 2213 2203 2206 2109 
2111 2110 2103 2102 2100 2201 2205 2212 2115 2114 2112 2100 2208 2103 2101 2210 2219 2223 2109 2110 2122 2106 2207 2102 2212 2210 2105 2211 2101 2203 2212 2230 2111 2110 2108 2106 2101 2215 2119 2141 2108 2201 2205 2206 2202 2218 2211 2215 2200 2227 
2106 2214 2215 2221 2100 2236 2219 2200 2229 2110 2202 2222 2222 2116 2123 2114 2106 2104 2103 2218 2126 2100 2204 2206 2207 2120 2111 2111 2107 2208 2214 2111 2127 2115 2107 2100 2213 2117 2100 2208 2114 2112 2208 2211 2212 2111 2124 2115 2112 21

In [57]:
def simulation_rattata_rattatac(t):
    M=np.zeros((50,50))
    M[0][0]=1100
    M[0][1]=1200
    cpt_ra=0
    cpt_rc=0
    for i in range(0,t):
        for x in list_ind(M):
            i,j=x
            Le=voisin(i,j)
            if M[i][j]//100==11:
                acc,Ma,Ar,Vide=rattataM(Le, M)                
            elif M[i][j]//100==12:   
                acc,Ma,Ar,Vide=rattataF(Le,M)
            elif M[i][j]//100==31:
                acc,Ma,Ar,Vide=rattatacM(Le,M)
            elif M[i][j]//100==32:
                acc,Ma,Ar,Vide=rattatacF(Le,M)
            vieillesse(M,i,j)
            if M[i,j]!=0:
                if len(acc)>0 and len(Vide)>0:
                    accouplement_r(i,j,Vide,acc,M)
                elif len(Vide)>0:
                    deplacement(i,j,Vide,M)
                evolution(i,j,M)
    for i in range(0,50):
        for j in range(0,50):
            if M[i,j]/1000==1:
                cpt_ra=cpt_ra+1
            if M[i,j]/1000==3:
                cpt_rc=cpt_rc+1
    print(cpt_ra)
    print(cpt_rc)
    return M
print_matrice(simulation_rattata_rattatac(50))

0
0
3143 1111 3134 3109 1117 1108 1104 1101 1202 1207 1209 1211 3226 1116 1103 1212 1115 1108 1104 1105 1112 1102 1201 1100 1112 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
3201 3212 3120 3128 1109 1102 1204 1213 1111 1109 1107 3227 1107 1209 3222 1109 1105 1100 1207 1207 1200 1205 1116 1103 0 1121 0 1111 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1118 1109 1102 1213 3202 3210 1110 1203 1207 1105 3103 3225 1111 1100 1205 1101 1202 1208 1213 1110 1206 1115 1100 1103 1112 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1213 1207 1118 1113 1203 1206 1207 1218 3100 3203 3211 1100 1210 1205 3222 1102 1116 1112 1103 1101 1201 1204 1100 0 1119 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1116 3112 3106 3133 3121 1115 3106 3202 3204 3211 3126 1108 1108 3122 1113 1101 1100 1205 1206 1100 0 1201 1202 1109 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 
1116 1112 1215 1111 1109 1214 3111 1114 3103 3235 1106 1102 1215 3122 1110 1214 1202 1204 1206 1103 1106 1100 0 0 0 1104 0

In [ ]:
def simulation_pokemon(t1,t2):
    M=simulation_rattata_rattatac(t1)
    for i in range(0,t2):
        for x in list_ind(M):
            i,j=x
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            if M[i][j]//100==11:
                acc,Ma,Ar,Vide=rattataM(Le,M)
            elif M[i][j]//100==12:   
                acc,Ma,Ar,Vide=rattataF(Le,M)
            elif M[i][j]//100==31:
                acc,Ma,Ar,Vide=rattatacM(Le,M)
            elif M[i][j]//100==32:
                acc,Ma,Ar,Vide=rattatacF(Le,M)
            elif M[i][j]//100==21:
                acc,Ma,Ar,Vide=mangloutonM(Le,M)
            elif M[i][j]//100==22:
                acc,Ma,Ar,Vide=mangloutonF(Le,M)
            elif M[i][j]//100==41:
                acc,Ma,Ar,Vide=argousteM(Le,M)
            elif M[i][j]//100==42:
                acc,Ma,Ar,Vide=argousteF(Le,M)
            vieillesse(M,i,j)
            if M[i][j]!=0:
                if len(Ma)>0 or len(Ar)>0:
                    manger(Ma,Ar,M,i,j)
                elif len(acc)>0 and len(Vide)>0:
                    accouplement(i,j,Vide,acc,M) 
                elif len(Vide)>0:
                    deplacement(i,j,Vide,M)
                evolution(i,j,M)
            
    return M
print_matrice(simulation_pokemon())

In [ ]:
for x in se:
    print(se)
    for y in se:
        if y % x == 0:
            se.discard(y)

In [ ]:
  M=[),(i+1,j+1),(i,j+1)]

In [ ]:
 np.random.choice(np.arange(0,3))


In [ ]:
np.random.choice(99)


In [ ]:
 np.random.choice(np.arange(1,3))

In [ ]:
np.random.choice(np.arange(0,4))

In [ ]:
import matplotlib.pyplot as plt
size = np.array(cells.shape)
dpi = 50.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig = plt.figure(figsize = figsize, dpi = dpi, facecolor = "white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon = False)
im=plt.imshow(cells, interpolation = 'nearest', cmap = plt.cm.gray_r)
plt.xticks([]), plt.yticks([])

import matplotlib.animation as a
def update():
    iterate(cells)
    im.set_array(cells)
    return im,

ani = a.FuncAnimation(fig, update, frames=range(20), interval=50)
plt.show()