## Deplacement d'un individu

In [31]:
import matplotlib

In [32]:
#les identifiants des pokemons:
#11**:rattata male
#12**:rattata femelle
#21**:manglouton male
#22**:manglouton femelle
#31**:rattatac male
#32**:rattatac femelle
#41**:argouste male
#42**:argouste femelle
#** représente l'âge de l'individu

In [33]:
import numpy as numpy

In [34]:
import numpy as np
#case vide
v=0
N=50
M=np.zeros((N,N))



In [35]:
#test
M[1][1]=1200
M[1][2]=1100
M


array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,  1200.,  1100., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [36]:
np.where(M == 1202)

(array([], dtype=int64), array([], dtype=int64))

In [37]:
M=np.zeros((N,N))
M[1][1]=1200
M[1][2]=1100
def vieillesse(M,i,j):
    if M[i][j]%100==99:
        M[i][j]=0
    else:
        M[i][j]=M[i][j]+1
        n=np.random.choice(99)      
        if M[i][j]%100>n:
            M[i][j]=0 
    return
vieillesse(M,1,1)
vieillesse(M,1,2)
M

array([[    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,  1201.,  1101., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       ..., 
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.],
       [    0.,     0.,     0., ...,     0.,     0.,     0.]])

In [55]:
def position(i,j):
    if i==0:
        if j==0:
            return "CoinSupG"
        elif j==len(M)-1:
            return "CoinSupD"
        else:
            return "CotHaut"
    elif j==0:
        if i==len(M)-1:
            return "CoinBasG"
        else :
            return "CotG"
    elif j==len(M)-1:
        if i==len(M)-1:
            return "CoinBasD"
        else:
            return "CotD"
    elif i==len(M)-1:
        return "CoteBas"
    else:
        return "Milieu"
position(1,1)

'Milieu'

In [39]:
N=50
M=np.zeros((N,N))
position(N-1,N-1)

'CoinBasD'

In [56]:
M=np.zeros((N,N))
M[1][1]=1200
M[1][2]=1100
def voisin(i,j):
    Le=[]#environnement
    if position(i,j)=="Milieu":
        Le=[(i-1,j-1),(i-1,j),(i-1,j+1),(i,j-1),(i,j+1),(i+1,j-1),(i+1,j),(i+1,j+1)]
    elif position(i,j)=="CoinSupG":
        Le=[(i,j+1),(i+1,j),(i+1,j+1)]
    elif position(i,j)=="CoinSupD":
        Le=[(i,j-1),(i+1,j),(i+1,j-1)]
    elif position(i,j)=="CoinBasG":
        Le=[(i,j+1),(i-1,j),(i-1,j+1)]
    elif position(i,j)=="CoinBasD":
        Le=[(i,j-1),(i-1,j),(i-1,j-1)]
    elif position(i,j)=="CotD":
        Le=[(i,j-1),(i-1,j),(i-1,j-1),(i+1,j),(i+1,j-1)]
    elif position(i,j)=="CotG":
        Le=[(i,j+1),(i-1,j),(i-1,j+1),(i+1,j+1)]
    elif position(i,j)=="CotBas":
        Le=[(i,j-1),(i-1,j-1),(i-1,j),(i-1,j+1),(i,j+1)]
    elif position(i,j)=="CotHaut":
        Le=[(i,j-1),(i+1,j-1),(i+1,j),(i+1,j+1),(i,j+1)]
    return Le

le=voisin(0,N-1)
le

[(0, 48), (1, 49), (1, 48)]

In [58]:
position(49,0)

'CoinBasG'

In [91]:

Vide=[]#liste des emplacements vides aux alentours
Ma=[]#liste des Mangloutons aux alentours
Ra=[]#liste des Rattatas aux alentours
Ar=[]#liste des Argoustes aux alentours
Rac=[]#liste des Rattatacs aux alentours
acc=[]#liste des potentiels partenaires pour l'accouplement


def rattataM(Le,Ar,Ma,Vide):
    #Ar=[]
    #Ma=[]
    #Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//1000==2:
            Ma.append(x)
        elif M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return

def rattataF(Le,Ar,Ma,acc,Vide):
    #Ar=[]
    #Vide=[]
    #acc=[]
    #Ma=[]
    for x in Le:
        i,j=x
        if M[i][j]//100==11 or M[i][j]//100==31:
            acc.append(x)
        elif M[i][j]//1000==2:
            Ma.append(x)
        elif M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return        

def rattatacM(Le,Ar,Vide):
    #Ar=[]
    #Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return 

def rattatacF(Le,Ar,acc,Vide):
    #Ar=[]
    #acc=[]
    #Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//1000==4:
            Ar.append(x)
        elif M[i][j]//100==11 or M[i][j]//100==31:
            acc.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return
            
def mangloutonM(Le,Vide):
    #Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append(x)
    return       
            
            
def mangloutonF(Le,acc,Vide):
    #acc=[]
    #Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]//100==21 or M[i][j]//100==41:
            acc.append(x)
        elif M[i][j]==0:
            Vide.append(x)
    return

def argousteM(Le,Vide):
    #Vide=[]
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append(x)
    return

def argousteF(Le,Vide,acc):
    #Vide=[]
    #acc=[]
    for x in Le:
        i,j=x
        if M[i][j]==0:
            Vide.append(x)
        elif M[i][j]//100==21 or M[i][j]//100==41:
            acc.append(x)
    return

rattataF(le,Ar,Ma,acc,Vide)
acc


[]

In [92]:
1200//1000*1000


1000

In [107]:
Vide=[]#liste des emplacements vides aux alentours
Ma=[]#liste des Mangloutons aux alentours
Ra=[]#liste des Rattatas aux alentours
Ar=[]#liste des Argoustes aux alentours
Rac=[]#liste des Rattatacs aux alentours
acc=[]#liste des potentiels partenaires pour l'accouplement

def evolution(i,j):
    if M[i][j]%100>=20 and (M[i][j]//1000==1 or M[i][j]//1000==2):
        n=np.random.choice(np.arange(1,11))
        if n*(M[i][j]%100-10)>50:
            M[i][j]=2000+M[i][j]
            print(M[i][j])
    return        
def manger(Ar,Ma,M,i,j):
    n=np.random.choice(np.arange(1,101))
    if M[i][j]//1000==1:
        if n<10*(len(Ma)+len(Ar)):
            M[i][j]=0
    elif M[i][j]//1000==3:
        if n<10*len(Ar):
            M[i][j]=0
    return i,j

def accouplement(i,j,Vide,acc):
    n=np.random.choice(np.arange(0,100))
    if len(acc)*10 > n:
        e=np.random.choice(np.arange(0,len(Vide)))
        sexe=np.random.choice(np.arange(1,3))
        x,y=Vide[e]
        M[x][y]=M[i][j]//1000*1000+sexe*100
    return
                       
def deplacement(i,j,Vide):
    e=np.random.choice(np.arange(0,len(Vide)))
    x,y=Vide[e]
    M[x,y]=M[i][j]
    M[i][j]=0    
    return    

                  
    

#def regroupement(M,Vide,i,j):
    Voisin2=[]
    c=0
    Rattatac=[]
    for s in Vide:
        c=0
        x,y=s
        if x==i-1 and y==j-1:
            Voisin2=[(i-2,j-2),(i-2,j-1),(i-2,j),(i-1,j-2),(i-1,j),(i,j-2),(i,j-1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                   if c==1:
                        Rattatac.append[m]
        if x==i-1 and y==j:
            Voisin2=[(i-2,j-1),(i-2,j),(i-2,j+1),(i-1,j-1),(i-1,j+1),(i,j-1),(i,j+1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
        if x==i-1 and y==j+1:
            Voisin2=[(i-2,j),(i-2,j+1),(i-2,j+2),(i-1,j),(i-1,j+2),(i,j+1),(i,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i and y==j-1:
            Voisin2=[(i-1,j-2),(i-1,j-1),(i-1,j),(i,j-2),(i+1,j-2),(i+1,j-1),(i+1,j)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i and y==j+1:
            Voisin2=[(i-1,j),(i-1,j+1),(i-1,j+2),(i,j+2),(i+1,j),(i+1,j+1),(i+1,j+2)]
          for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j-1:
            Voisin2=[(i,j-2),(i,j-1),(i+1,j-2),(i+1,j),(i+2,j-2),(i+2,j-1),(i+2,j)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j:
            Voisin2=[(i,j-1),(i,j+1),(i+1,j-1),(i+1,j+1),(i+2,j-1),(i+2,j),(i+2,j+1)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]
        if x==i+1 and y==j+1:
            Voisin2=[(i,j+1),(i,j+2),(i+1,j),(i+1,j+2),(i+2,j),(i+2,j+1),(i+2,j+2)]
            for m in Voisin2:
                a,b=m
                if M[a][b]//1000==3:
                    c=c+1
                    if c==1:
                        Rattatac.append[m]    

In [108]:
def matrice_alea(N):
    
    M=np.zeros((N,N))
    for i in range (0,N):
        for j in range (0,N):
            al_e=np.random.choice(np.arange(0,5))
            al_s=np.random.choice(np.arange(1,3))
            al_a=np.random.choice(np.arange(0,100))
            if al_e==0:
                M[i][j]=1000+al_s*100+al_a
            elif al_e==1:
                M[i][j]=2000+al_s*100+al_a
            elif al_e==2:
                M[i][j]=3000+al_s*100+al_a
            elif al_e==3:
                M[i][j]=4000+al_s*100+al_a
            elif al_e==4:
                M[i][j]=0
    return M
Matrice=matrice_alea(50)
Matrice

array([[ 2198.,  1102.,  2126., ...,  4181.,  2179.,  3231.],
       [ 3100.,  2130.,  1269., ...,  4246.,  4223.,  4273.],
       [    0.,  2107.,  1229., ...,     0.,  4133.,  4136.],
       ..., 
       [ 3162.,  1100.,     0., ...,  2118.,  2273.,  1210.],
       [ 2270.,     0.,  1159., ...,  4185.,  4126.,  2177.],
       [ 2160.,  4196.,  3223., ...,     0.,     0.,  1142.]])

In [109]:
voisin(49,1)

[]

In [110]:
M[0,3]=1235
evolution(0,3)


3235.0


In [111]:
M[0,0]=1245
M[0,1]=1114
M[1,0]=0
vide=[(1,0)]
acc=[(0,1)]
accouplement(0,0,vide,acc)
M[(0,0)]
M[1,0]

1200.0

In [124]:
def list_ind(M):
    L_ind=[]
    for i in range (0,len(M)):
        for j in range (0,len(M)):
            if M[i][j]!=0:
                L_ind.append((i,j))
    return L_ind
list_ind(Matrice)

[(0, 0),
 (0, 1),
 (0, 2),
 (0, 3),
 (0, 5),
 (0, 6),
 (0, 7),
 (0, 8),
 (0, 9),
 (0, 10),
 (0, 11),
 (0, 12),
 (0, 13),
 (0, 14),
 (0, 15),
 (0, 16),
 (0, 17),
 (0, 18),
 (0, 19),
 (0, 21),
 (0, 22),
 (0, 23),
 (0, 24),
 (0, 25),
 (0, 26),
 (0, 27),
 (0, 28),
 (0, 29),
 (0, 30),
 (0, 31),
 (0, 32),
 (0, 33),
 (0, 34),
 (0, 35),
 (0, 36),
 (0, 37),
 (0, 38),
 (0, 39),
 (0, 40),
 (0, 41),
 (0, 42),
 (0, 43),
 (0, 44),
 (0, 45),
 (0, 46),
 (0, 47),
 (0, 48),
 (0, 49),
 (1, 0),
 (1, 1),
 (1, 2),
 (1, 3),
 (1, 4),
 (1, 5),
 (1, 7),
 (1, 9),
 (1, 11),
 (1, 12),
 (1, 13),
 (1, 15),
 (1, 16),
 (1, 17),
 (1, 18),
 (1, 19),
 (1, 21),
 (1, 22),
 (1, 23),
 (1, 24),
 (1, 25),
 (1, 26),
 (1, 27),
 (1, 29),
 (1, 30),
 (1, 32),
 (1, 33),
 (1, 35),
 (1, 36),
 (1, 38),
 (1, 40),
 (1, 41),
 (1, 42),
 (1, 43),
 (1, 44),
 (1, 45),
 (1, 46),
 (1, 47),
 (1, 48),
 (1, 49),
 (2, 1),
 (2, 2),
 (2, 3),
 (2, 4),
 (2, 5),
 (2, 6),
 (2, 7),
 (2, 8),
 (2, 9),
 (2, 11),
 (2, 13),
 (2, 14),
 (2, 15),
 (2, 16),
 (2, 1

In [ ]:
def individu(x,M):
    i,j=x
    return M[i][j]

In [103]:

def simulation():
    M=matrice_alea(50)
    for i in range(0,len(M)):
        for j in range(0,len(M)):
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            
            if M[i][j]//100==11:
                rattataM(Le,Ar,Ma,Vide)
            elif M[i][j]//100==12:   
                rattataF(Le,acc,Ma,Ar,Vide)
            elif M[i][j]//100==31:
                rattatacM(Le,Ar,Vide)
            elif M[i][j]//100==32:
                rattatacF(Le,Ar,acc,Vide)
            elif M[i][j]//100==21:
                mangloutonM(Le,Vide)
            elif M[i][j]//100==22:
                mangloutonF(Le,acc,Vide)
            elif M[i][j]//100==41:
                argousteM(Le,Vide)
            elif M[i][j]//100==42:
                argousteF(Le,Vide,acc)
            if len(Ma)>0 or len(Ar)>0:
                manger(Ma,Ar,M,i,j)
            elif len(acc)>0 and len(Vide)>0:
                accouplement(i,j,Vide) 
            elif len(Vide)>0:
                deplacement(i,j,Vide)
            evolution(i,j)
            vieillesse(M,i,j)
                
    return M
simulation()

array([[  0.00000000e+00,   0.00000000e+00,   3.15400000e+03, ...,
          0.00000000e+00,   1.14700000e+03,   0.00000000e+00],
       [  1.00000000e+00,   0.00000000e+00,   0.00000000e+00, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  0.00000000e+00,   1.00000000e+00,   4.13200000e+03, ...,
          3.15100000e+03,   0.00000000e+00,   4.25500000e+03],
       ..., 
       [  1.15000000e+03,   1.10700000e+03,   2.28400000e+03, ...,
          0.00000000e+00,   0.00000000e+00,   0.00000000e+00],
       [  2.14800000e+03,   3.10200000e+03,   1.00000000e+00, ...,
          1.00000000e+00,   2.18400000e+03,   0.00000000e+00],
       [  4.27300000e+03,   0.00000000e+00,   1.27300000e+03, ...,
          0.00000000e+00,   2.21300000e+03,   1.00000000e+00]])

In [125]:
    def simulation():
        M=matrice_alea(50)
        for x in list_ind(M):
            i,j=x
            acc=[]
            Ma=[]
            Ar=[]
            Vide=[]
            Le=voisin(i,j)
            
            if M[i][j]//100==11:
                rattataM(Le,Ar,Ma,Vide)
            elif M[i][j]//100==12:   
                rattataF(Le,acc,Ma,Ar,Vide)
            elif M[i][j]//100==31:
                rattatacM(Le,Ar,Vide)
            elif M[i][j]//100==32:
                rattatacF(Le,Ar,acc,Vide)
            elif M[i][j]//100==21:
                mangloutonM(Le,Vide)
            elif M[i][j]//100==22:
                mangloutonF(Le,acc,Vide)
            elif M[i][j]//100==41:
                argousteM(Le,Vide)
            elif M[i][j]//100==42:
                argousteF(Le,Vide,acc)
            if len(Ma)>0 or len(Ar)>0:
                manger(Ma,Ar,M,i,j)
            elif len(acc)>0 and len(Vide)>0:
                accouplement(i,j,Vide) 
            elif len(Vide)>0:
                deplacement(i,j,Vide)
            evolution(i,j)
            vieillesse(M,i,j)
                
        return M
simulation()

array([[    0.,  2127.,     0., ...,     0.,  4126.,     0.],
       [ 4119.,     0.,     0., ...,  4101.,  1143.,     0.],
       [    0.,     0.,     0., ...,  4165.,     0.,  1241.],
       ..., 
       [    0.,     0.,  3222., ...,  4132.,     0.,  2118.],
       [    0.,  1105.,  2212., ...,     0.,     0.,     0.],
       [ 2204.,  2263.,     0., ...,     0.,     0.,     0.]])

In [119]:
se = set((4,5,2,3,6,7))

In [122]:
for x in se:
    print(se)
    for y in se:
        if y % x == 0:
            se.discard(y)

{2, 3, 4, 5, 6, 7}


RuntimeError: Set changed size during iteration

In [ ]:
  M=[),(i+1,j+1),(i,j+1)]

In [ ]:
 np.random.choice(np.arange(0,3))


In [ ]:
np.random.choice(99)


In [ ]:
 np.random.choice(np.arange(1,3))

In [ ]:
np.random.choice(np.arange(0,4))

In [ ]:
import matplotlib.pyplot as plt
size = np.array(cells.shape)
dpi = 50.0
figsize= size[1]/float(dpi),size[0]/float(dpi)
fig = plt.figure(figsize = figsize, dpi = dpi, facecolor = "white")
fig.add_axes([0.0, 0.0, 1.0, 1.0], frameon = False)
im=plt.imshow(cells, interpolation = 'nearest', cmap = plt.cm.gray_r)
plt.xticks([]), plt.yticks([])

import matplotlib.animation as a
def update():
    iterate(cells)
    im.set_array(cells)
    return im,

ani = a.FuncAnimation(fig, update, frames=range(20), interval=50)
plt.show()